---
namespace: agservicenow
name: agservicenow
readme: README.md
authors:
- "Paul Knight <paul.knight@delaware.gov>"
- "Tim Rightnour <thegarbledone@gmail.com>"
- "Will Tome (@willtome)"
- "Alex Mittell (@alex_mittell)"
description: >
    The Service Now modules previously packaged as part of Ansible, now
    in a Collection distributed via Ansible Galaxy.  snow_record creates,
    updates or deletes a record in a specified table in the Service Now
    instance. snow_record_find retrieves one or more records based on the
    supplied query.
    ServiceNow Inventory Plugin for using ServiceNow CMDB as a dynamic 
    inventory source.
repository: https://github.com/aglenn360/agservicenow.agservicenow.git
documentation: https://github.com/aglenn360/agservicenow.agservicenow.git/wiki
homepage: https://github.com/aglenn360/agservicenow.agservicenow.git
issues: https://github.com/aglenn360/agservicenow.agservicenow.git/issues
